spring:
  application:
    name: customer
  profiles: dev

server:
  port: 8088
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8384/eureka

name: dev


---
spring:
  application:
    name: customer
  profiles: test

server:
  port: 8088
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8384/eureka

name: test